# Generated by Django 5.1.2 on 2024-10-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_cliente_cnpj_cliente_protheus_cliente_razaosocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fardo',
            field=models.IntegerField(default=0),
        ),
    ]
