# Generated by Django 5.1.2 on 2024-10-16 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_alter_endereco_cidade_alter_endereco_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.categoria'),
        ),
    ]
