# Generated by Django 5.1.2 on 2024-10-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_grupo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
