# Generated by Django 5.1.2 on 2024-10-16 13:55

import loja.nome_imagem
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_categoria_slug_grupo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=loja.nome_imagem.produto_imagem_path),
        ),
    ]
