# Generated by Django 5.1.2 on 2024-10-16 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0012_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensorcamento',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loja.orcamento'),
        ),
    ]
