# Generated by Django 5.1.2 on 2024-10-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0013_alter_itensorcamento_orcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='codigo_orcamento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
