# Generated by Django 5.1.2 on 2024-10-17 20:58

import django.db.models.deletion
import loja.criarformcheckout
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0014_alter_orcamento_codigo_orcamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentosSalvos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulario', models.FileField(upload_to=loja.criarformcheckout.produto_formulario_path)),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loja.orcamento')),
            ],
        ),
    ]
