# Generated by Django 5.1.2 on 2024-10-27 18:01

import django.db.models.deletion
import loja.nome_imagem
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0015_orcamentossalvos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=loja.nome_imagem.produto_imagem_path)),
                ('quantidade', models.IntegerField(default=0)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.produto')),
            ],
        ),
    ]
