# Generated by Django 5.1.2 on 2024-10-27 18:39

import loja.nome_imagem
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0016_remove_produto_imagem_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=loja.nome_imagem.produto_imagem_path),
        ),
        migrations.DeleteModel(
            name='Fotos',
        ),
    ]
