# Generated by Django 5.1.2 on 2024-10-27 18:44

import loja.nome_imagem
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0017_produto_imagem_delete_fotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=loja.nome_imagem.produto_imagem_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='loja.fotos'),
        ),
    ]
