# Generated by Django 5.1.2 on 2024-10-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0019_rename_fotos_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='texto',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
    ]
